# Generated by Django 3.0.7 on 2020-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('Option_1', models.CharField(max_length=100)),
                ('Option_2', models.CharField(max_length=100)),
                ('Option_3', models.CharField(max_length=100)),
                ('Option_4', models.CharField(max_length=100)),
                ('Option_5', models.CharField(max_length=100)),
                ('Reason_if_match_percent_greater_than_50', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'post_check_results',
            },
        ),
    ]
